In [37]:
import numpy as np
from sklearn import linear_model

In [3]:
testdata = np.random.normal(size=(100,100,30,2))

In [4]:
def interaction_test(groups,data):
    

(100L, 100L, 30L, 2L)

In [91]:
def build_group_matrix(n1,n2):
    """build a design matrix encoding only group"""
    x = np.zeros(shape=(2*(n1+n2),2))
    x[:,0]=1
    x[2*(n1+1):2*(n1+n2),1]=1
    return x

In [107]:
def build_time_matrix(n1,n2):
    x = np.zeros(shape=(2*(n1+n2),2))
    x[:,0]=1
    x[1:(2*(n1+n2)):2,1]=1
    return x

In [140]:
def build_main_matrix(n1,n2):
    x1 = build_group_matrix(n1,n2)
    x2 = build_time_matrix(n1,n2)[:,1,None]
    x = np.concatenate((x1,x2),axis=1)
    return x

In [141]:
def build_full_matrix(n1,n2):
    x1 = build_group_matrix(n1,n2)
    x2 = build_time_matrix(n1,n2)[:,1,None]
    x = np.concatenate((x1,x2,x2),axis=1)
    x[0:(n1+n2),3]=0
    return x

In [143]:
def build_sub_matrix(n1,n2):
    n = n1 + n2
    x = np.zeros(shape=(n*2,n))
    for ind in np.arange(0,n):
        x[ind*2:(ind*2+2),ind]=1
    return x

In [144]:
build_sub_matrix(3,3)

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

## Steps
1. build design matrix
2. do OLS regression
3. get p-values for three contrasts
4. conjunction of p-values

design matrix: n * 4
G1T1, G1T2, G2T1, G2T2

In [43]:
x = build_design_matrix(10,10)
y = np.random.normal(size=(40))

In [46]:
def fit_ols(x,y):
    clf = linear_model.LinearRegression(fit_intercept=False)
    clf.fit(x,y)
    return clf

In [49]:
mymod = fit_ols(x,y)

In [51]:
def ss_sub(y,n1,n2):
    

array([ 0.03964523,  0.45252091,  0.24293989,  0.61850413])

In [ ]:
def ss_group

In [ ]:
def ss_time

In [ ]:
def ss_int

In [ ]:
np.linalg.pinv()

In [149]:
def ss_partition(x,y):
    """for design matrix x and observations y,
    do OLS and partition sums of squares
    SStot: Fr(Y)
    SSerr: Fr(Y-Yhat)
    SSexp: SStot - SSerr"""
    y = y-np.mean(y)
    hat = np.dot(x,np.linalg.pinv(x))
    yhat = np.dot(hat,y)
    sstot = np.sum(np.square(y))
    sserr = np.sum(np.square(y-yhat))
    ssexp = sstot - sserr
    return [sstot,sserr,ssexp]

In [148]:
# test case
n1=10
n2=10
y = np.random.normal(size=(40))
y = y - np.mean(y)

print ss_partition(build_group_matrix(n1,n2),y)
print ss_partition(build_time_matrix(n1,n2),y)
print ss_partition(build_main_matrix(n1,n2),y)
print ss_partition(build_full_matrix(n1,n2),y)
print ss_partition(build_sub_matrix(n1,n2),y)

ss_group=ss_partition(build_group_matrix(n1,n2),y)[2]
ss_time=ss_partition(build_time_matrix(n1,n2),y)[2]
ss_interaction = ss_partition(build_full_matrix(n1,n2),y)[2] - ss_partition(build_main_matrix(n1,n2),y)[2]



[26.695295930382088, 25.447177833388853, 1.2481180969932346]
[26.695295930382088, 25.350333361901065, 1.3449625684810229]
[26.695295930382088, 24.102215264907834, 2.593080665474254]
[26.695295930382088, 23.586697995057108, 3.1085979353249797]
[26.695295930382088, 11.355826330480628, 15.339469599901459]


In [76]:
# ss group: ss_resid_null - ss_resid_group
ss_resid()

array([[ 1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  